DOMAIN = "tagging_and_lyrics"
CONF_HOST = "host"
CONF_ACCESS_KEY = "access_key"
CONF_ACCESS_SECRET = "access_secret"
CONF_PORT = "port"
CONF_MEDIA_PLAYER = "media_player"
CONF_LYRICS_ENABLE = "lyrics_enable"
